site_name: UserOwnIoT
site_description: Open, privacy-first IoT projects
site_author: userowniot

nav:
  - About: index.md
  - Projects: projects.md
  - Contact: contact.md

theme:
  name: material
  language: en
  palette:
    primary: lime
    accent: indigo
  logo: images/logo.png
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
